name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          path: repo

      - name: "Checkout Weaver-UI-Core"
        uses: actions/checkout@v3
        with:
          repository: TAMULib/Weaver-UI-Core
          path: weaver-ui
          ref: 2.x

      - name: "Run Weaver-UI-Core Docker Compose Registry Image"
        run: docker-compose -f $GITHUB_WORKSPACE/weaver-ui/docker-compose.yml up -d registry

      - name: "Publish Weaver-UI-Core (@wvr/core)"
        run: |
          cd $GITHUB_WORKSPACE/weaver-ui
          npm run publish:local

      - name: "Install Chrome Drivers"
        run: sudo apt-get install xvfb

      - name: "Node Cache"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Node Modules Cache"
        uses: actions/cache@v3
        with:
          path: $GITHUB_WORKSPACE/repo/node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install Node"
        run: |
          cd $GITHUB_WORKSPACE/repo
          npm install --registry=http://localhost:4873

      - name: "Run Node Tests"
        run: |
          cd $GITHUB_WORKSPACE/repo
          xvfb-run --auto-servernum npm run test:ci
